### ISSUE TITLE
problem running script.  ( prolly something im doing wrong)

### ISSUE THREAD

**Issue by ph33rz** [KanekiX2/Email-Osint#2]
hello i was hoping for a little assistants i seen you ran the script using py Email-Osint.py    however when i tried this method i was unable to get any results,  i installed pythonpy and was still unable.   Using python3 this is a copy of what i got as an error.     i install requirements using pip3 and tried to run using python3 Email-Osint.

`[ph33rz@server Email-Osint]$ python3 EmailOsint.py -e test@test.net

                         Author : Kaneki | Github : github.com/KanekiX2 | Discord : discord.gg/vGKQs4Cczy
sh: line 1: title: command not found
sh: line 1: Email: command not found

> Email Réputation:
-------------------
Emailrep.io API limit reached. Try again tomorrow.
sh: line 1: title: command not found
sh: line 1: Email: command not found

> Email Vérification:
---------------------
Verify-email.org API limit reached. Try again in 1 hour.
sh: line 1: title: command not found
sh: line 1: Dump: command not found

> Dump pastebin:
----------------
> https://pastebin.com/raw/Wd26TdtB
^C[!] Your adresse IP has banned, retry tomorrow or change your ip.                                                                                 
> https://pastebin.com/raw/J0BEFsQN
> https://pastebin.com/raw/R1vqapbr                                                                                                                 
^C[!] Your adresse IP has banned, retry tomorrow or change your ip.                                                                                 
^X^C[!] Your adresse IP has banned, retry tomorrow or change your ip.
sh: line 1: Breached: command not found
sh: line 1: title: command not found

> Breached Leaks Website:
-------------------------
^Z
[1]+  Stopped                 python3 EmailOsint.py -e test@test.net
`

**Comment by KanekiWeb** [comment]
Email Osint is more recommended for Windows you must be on linux I suppose and also check that you have correctly set the API keys if you have them.

**Comment by ph33rz** [comment]
ahhh didnt even realize it was more setup for windows and yes i am on arch.   ty will do.
